services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vendari-front
    ports:
      - "4400:4400"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
